name: Config Entity Source
description: Config entity source plugin for the Translation Management system.
package: Translation Management
# core: 8.x
type: module

dependencies:
 - tmgmt
 - config_translation
 - block

# Information added by Drupal.org packaging script on 2017-01-24
version: '8.x-1.1'
core: '8.x'
project: 'tmgmt'
datestamp: 1485289087
