advagg.settings:
  type: config_entity
  label: Settings
  mapping:
    css:
      type: mapping
      label: 'CSS settings'
      mapping:
        combine_media:
          type: boolean
          label: 'Combine multiple media selectors per aggregate.'
        fix_type:
          type: boolean
          label: 'Fix type of added asset files.'
        ie:
          type: mapping
          label: 'Internet Explorer specific CSS settings.'
          mapping:
            limit_selectors:
              type: boolean
              label: 'IE9 & under have problems with css files with more than 1095 selectors.'
            selector_limit:
              type: integer
              label: 'Number of selectors to limit to.'
        via_js:
          type: boolean
          label: 'If true then the css is being rendered via javascript'
    dns_prefetch:
      type: boolean
      label: 'Prefetch external domains for css/js'
    path:
      type: mapping
      label: 'Path/Url settings'
      mapping:
        convert:
          type: mapping
          label: 'What conversions to apply.'
          mapping:
            absolute_to_protocol_relative:
              type: boolean
              label: 'Convert absolute path css/js src/url() to be protocol relative'
            force_https:
              type: boolean
              label: 'Convert absolute path css/js src/url() to use https://'
    cache_level:
      type: integer
      label: 'Level of caching for AdvAgg to use.'
    core_groups:
      type: boolean
      label: Use core grouping algorithm.
    cron_frequency:
      type: integer
      label: frequency to run the AdvAgg cron maintenance functions.
    debug:
      type: boolean
      label: 'Enable debug mode.'
    enabled:
      type: boolean
      label: 'Enable AdvAgg.'
    global_counter:
      type: integer
      label: 'Counter to force new aggregates through caches etc.'
    include_base_url:
      type: boolean
      label: 'Include the base url in the aggregates hash.'
    js_fix_type:
      type: boolean
      label: 'Fix type of added asset files.'
    root_dir_prefix:
      type: string
      label: 'Default root dir for the advagg files; controls advagg_get_root_files_dir().'
    serializer:
      type: string
      label: 'Function to use when converting a non scalar to a string'
    skip_enabled_preprocess_check:
      type: boolean
      label: 'Skip preprocess check on status page'
    show_bypass_cookie_message:
      type: boolean
      label: 'Display a message when the bypass cookie is active.'
