id: d7_advagg_settings
label: AdvAgg configuration
migration_tags:
  - Drupal 7
source:
  plugin: variable
  variables:
    - advagg_core_groups
    - advagg_cron_frequency
    - advagg_enabled
    - advagg_include_base_url
    - advagg_js_fix_type
    - advagg_cache_level
    - advagg_convert_absolute_to_protocol_relative_path
    - advagg_browser_dns_prefetch
    - advagg_combine_css_media
    - advagg_force_https
    - advagg_css_fix_type

process:
  cache_level: advagg_cache_level
  core_groups: advagg_core_groups
  cron_frequency: advagg_cron_frequency
  enabled: advagg_enabled
  include_base_url: advagg_include_base_url
  js_fix_type: advagg_js_fix_type
  dns_prefetch: advagg_browser_dns_prefetch
  'css/combine_media': advagg_combine_css_media
  'css/fix_type': advagg_css_fix_type
  'path/convert/absolute_to_protocol_relative': advagg_convert_absolute_to_protocol_relative_path
  'path/convert/force_https': advagg_force_https
destination:
  plugin: config
  config_name: advagg.settings
