site_key: 6LeOWwgUAAAAAAQ1kXmXQS14wfhqDUeNkeuqxYcl
secret_key: 6LeOWwgUAAAAABG0RvM_dwMgYL7cTDGPwGvRQCuI
widget:
  theme: light
  type: image
  size: ''
  tabindex: 0
  noscript: false
_core:
  default_config_hash: ZKQ03ePk4sH2zESRw4tdZYw__nG2YN4Ru5roPL23g3A
