<?php

/**
 * @file
 * Slick carousel integration, the last carousel you'll ever need.
 */

use Drupal\blazy\Blazy;
use Drupal\slick\SlickDefault;

/**
 * Implements hook_theme().
 */
function slick_theme() {
  $themes = [];
  $items  = ['slick', 'slide', 'grid', 'image', 'thumbnail', 'vanilla', 'wrapper'];
  foreach ($items as $item) {
    $key = $item == 'slick' ? $item : 'slick_' . $item;
    $themes[$key] = [
      'render element' => 'element',
      'file' => 'templates/slick.theme.inc',
    ];
  }
  return $themes;
}

/**
 * Implements hook_library_info_build().
 */
function slick_library_info_build() {
  $libraries['slick.css'] = [
    'dependencies' => ['slick/slick'],
    'css' => [
      'theme' => ['/libraries/slick/slick/slick-theme.css' => []],
    ],
  ];

  $manager = \Drupal::service('slick.manager');
  foreach ($manager::getConstantSkins() as $group) {
    if ($skins = $manager->getSkinsByGroup($group)) {
      foreach ($skins as $key => $skin) {
        $provider = isset($skin['provider']) ? $skin['provider'] : 'slick';
        $id = $provider . '.' . $group . '.' . $key;
        if (isset($skin['css']) && is_array($skin['css'])) {
          $libraries[$id]['css'] = $skin['css'];
        }
        if (isset($skin['js']) && is_array($skin['js'])) {
          $libraries[$id]['js'] = $skin['js'];
        }
      }
    }
  }
  return $libraries;
}

/**
 * Implements hook_config_schema_info_alter().
 */
function slick_config_schema_info_alter(array &$definitions) {
  $settings = SlickDefault::extendedSettings();
  Blazy::configSchemaInfoAlter($definitions, 'slick_base', $settings);
}

/**
 * Implements hook_hook_info().
 */
function slick_hook_info() {
  $hooks['slick_skins_info'] = ['group' => 'slick'];
  return $hooks;
}

/**
 * Implements hook_library_info_alter().
 */
function slick_library_info_alter(&$libraries, $extension) {
  if ($extension === 'slick' && function_exists('libraries_get_path')) {
    $libraries['slick']['js'] = ['/' . libraries_get_path('slick') . '/slick/slick.min.js' => []];
    $libraries['slick']['css']['base'] = ['/' . libraries_get_path('slick') . '/slick/slick.css' => []];
    $libraries['slick.css']['css']['theme'] = ['/' . libraries_get_path('slick') . '/slick/slick-theme.css' => []];
  }

  // Update the blazy/media library to depend on the slick/slick library.
  if ($extension === 'blazy' && isset($libraries['media'])) {
    $libraries['media']['dependencies'][] = 'slick/slick';
  }
}
