slick_media:
  type: slick_extended
  label: 'Slick media base display format settings'
  mapping:
    color_field:
      type: string
      label: 'Color'
    nested_slick:
      type: boolean
      label: 'Enable nested slick'
    nested_optionset:
      type: string
      label: 'Nested optionset'
    nested_style:
      type: string
      label: 'Nested style'

field.formatter.settings.slick_media:
  type: slick_media
  label: 'Slick media display format settings'
