<?php

/**
 * @file
 * Contains eminent_custom.module.
 */
use Drupal\Core\Entity\EntityInterface;
use Drupal\node\NodeInterface;
use Drupal\node\NodeTypeInterface;
use Drupal\node\Entity\Node;
use Drupal\Core\Url;
use Drupal\Component\Utility\Unicode;

/**
 * Implements hook_ENTITY_TYPE_presave.
 */
function eminent_custom_paragraph_presave(EntityInterface $entity) {
  // Checks whether the paragraph type is time line.
  $entity_type = $entity->getType();
  if ($entity_type == "time_line_story") {
    $time_line_story = $entity->get('field_time_line_media_reference')->target_id;
    $from_media_entity = $entity->get('field_time_line_from_media')->value;
    // If from media checkbox is checked for paragraph, save the data
    // from entity, into the time line.
    if ($from_media_entity) {
      $media = entity_load('media', $time_line_story);
      $media_type = $media->getType();
      $description = $media->get('field_dc_description')->value;
      $image = $media->thumbnail->target_id;
      $entity->field_time_line_image->target_id = $image;
      $title = $media->get('field_dc_title')->value;
      $date = $media->get('field_dc_date')->value;
      $media_url = Url::fromRoute('entity.media.canonical', array('media' => $time_line_story));
      $media_url = \Drupal::l($title, $media_url);
      $description = Unicode::truncate($description, 70);
      $entity->field_time_line_description->setValue($description);
      $entity->field_time_line_title->setValue($title);
      $entity->field_time_line_date->setValue($date);
    }
  }
}
