custom_solr_search.custom_solr_search_filter_query.*:
  type: config_entity
  label: 'Custom solr search filter query config'
  mapping:
    id:
      type: string
      label: 'ID'
    label:
      type: label
      label: 'Label'
    server:
      type: string
      label: 'Server'
    filter:
      type: string
      label: 'Filter'
    uuid:
      type: string
