<?php

/**
 * @file
 * Slick Quiz Views module help and theme functions.
 */

// Store Slick Quiz preprocess theme functions in a separate .inc file.
\Drupal::moduleHandler()->loadInclude('slick_quiz', 'inc', 'slick_quiz.theme');

/**
 * Implements hook_theme().
 */
function slick_quiz_theme($existing, $type, $theme, $path) {
  return array(
    'slick_quiz' => array(
      'file' => 'slick_quiz.theme.inc',
    ),
  );
}
