advagg_js_minify.settings:
  type: config_entity
  label: Settings
  mapping:
    add_license:
      type: boolean
      label: 'Add licensing information to aggregates for individual source files.'
    file_settings:
      type: sequence
      label: 'Per file minification settings.'
      sequence:
        type: mapping
        mapping:
          path:
            type: string
            label: 'File path to asset.'
          minifier:
            type: integer
            label: 'Which minifier to use for this file. 0 is disabled.'
    minifier:
      type: integer
      label: 'Minifier to use. 0 is disabled.'
    ratio_max:
      type: float
      label: 'Upper bound comparison value for the minification ratio test.'
    ratio_min:
      type: float
      label: 'Lower bound comparison value for the minification ratio test.'
