<?php

/**
 * @file
 * Contains curtain_raiser.module.
 */
use Drupal\Core\Entity\EntityInterface;
use Drupal\node\NodeInterface;
use Drupal\node\NodeTypeInterface;
use Drupal\node\Entity\Node;
use Drupal\Core\Url;
use Drupal\Component\Utility\Unicode;

function curtain_raiser_page_top(array &$page_top) {
  $config = \Drupal::service('config.factory')->getEditable('curtain_raiser.settings');

  $inauguration_status = $config->get('inauguration_status');
  $master_password = $config->get('master_password');
  $heading = $config->get('heading');
  $content = $config->get('content');

  if (!$inauguration_status && $master_password!='') {
    $form = \Drupal::formBuilder()->getForm('\Drupal\curtain_raiser\Form\InaugurationForm');
    $page_top['form'] = $form;
    $page_top['form']['#prefix'] = '
      <div class="container-ing">
        <div id="effect">
          <img src="/modules/custom/curtain_raiser/images/curtain.jpg" id="curtain1">
          <img src="/modules/custom/curtain_raiser/images/curtain.jpg" id="curtain2">
          <div class="content-ing">
            <div>
              <h1>'.$heading.'</h1>
              <p>'.$content.'</p>
            ';
      $page_top['form']['#suffix'] = '</div>
        </div>
      </div>
    </div>';

    $page_top['#attached']['library'][] = 'curtain_raiser/curtain_raiser';
    return $page_top;
  }

}
