tmgmt_content.settings:
  type: config_entity
  mapping:
    embedded_fields:
      label: 'Embedded fields'
      type: sequence
      sequence:
        type: sequence
        sequence:
          type: boolean
